version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: portainer_portainer_business_1
      APP_PORT: 9500
    container_name: portainer_app_proxy_1
  docker:
    image: >-
      docker:27.2.0-dind@sha256:f9f72ad901a78f27be922b2d320bbc263174f12919c1b37e6a01f828fa904565
    privileged: true
    network_mode: host
    stop_grace_period: 1m
    restart: on-failure
    environment:
      DOCKER_ENSURE_BRIDGE: dind0:10.32.0.1/16
    entrypoint: /entrypoint.sh
    command: |
      dockerd
        --bridge dind0
        --data-root /data/data
        --exec-root /data/exec
        --host unix:///data/docker.sock
        --pidfile /data/docker.pid
    volumes:
      - ${APP_DATA_DIR}/entrypoint.sh:/entrypoint.sh
      - ${APP_DATA_DIR}/data/docker:/data
    container_name: portainer_docker_1
  portainer:
    image: >-
      portainer/portainer-ee:2.33.1@sha256:5c1a782e9cfe0bfb41522b9c2af334289d19cb7f164426c0bfb9ce3b454b69e7
    command: '--host unix:///var/run/docker.sock --admin-password-file=/default-password'
    ports:
      - "9500:9000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/default-password:/default-password
      - ${APP_DATA_DIR}/data/portainer:/data
      - ${APP_DATA_DIR}/data/docker:/var/run
    container_name: portainer_portainer_business_1
